version: "3.2"

services:
  # PHP
  php:
    build: './docker/php/'
    restart: always
    networks:
      - backend
    volumes:
      - .:/var/www/html/

  # Apache
  apache:
    build: './docker/apache/'
    restart: always
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/

  # MySQL
  mysql:
    build: './docker/mysql/'
    restart: always
    ports:
      - "3307:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

networks:
  frontend:
  backend: