version: "3.2"

services:
  php:
    build: './docker/php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/

  apache:
    build: './docker/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/

  mysql:
    build: './docker/mysql/'
    ports:
      - "3307:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

networks:
  frontend:
  backend: