### STAGE 1: Build ###
# FROM node:12.7-alpine AS build

# WORKDIR /usr/src/app
# RUN mkdir angular-module
# COPY src/angular-module/package.json ./angular-module/package.json

# WORKDIR /usr/src/app/angular-module
# RUN npm install
# COPY . .
# # RUN npm run build

# # ### STAGE 2: Run ###
# # FROM nginx:1.17.1-alpine
# # COPY --from=build /usr/src/app/dist/angular-module /usr/share/nginx/html






# CMD tail -f /dev/null